name: Continuous integration workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test:cov
      - name: Run e2e tests
        run: npm run test:e2e
